name: Track Template Usage

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get_repositories_list:
    if: github.repository == 'maael/next-template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Template Repository Usage Action
        uses: maael/template-repository-usage-action@v1.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
